export type TeamRoleId = 'planner' | 'implementer' | 'reviewer' | 'tester';

export const REQUIRED_TEAM_ROLES: TeamRoleId[] = ['planner', 'implementer', 'reviewer'];

export const ALLOWED_TEAM_ROLES: TeamRoleId[] = [...REQUIRED_TEAM_ROLES, 'tester'];

export interface TeamRoleDefinition {
  agent: string;
  instructions: string;
}

export interface AgentTeamDefinition {
  version: 1;
  id: string;
  title: string;
  orchestrator?: { agent: string };
  roles: {
    planner: TeamRoleDefinition;
    implementer: TeamRoleDefinition;
    reviewer: TeamRoleDefinition;
    tester?: TeamRoleDefinition;
  };
}

export interface AgentTeamValidationResult {
  definition?: AgentTeamDefinition;
  errors: string[];
}

const FORBIDDEN_ROLE_KEYS = new Set(['sideEffects', 'output', 'prompt']);

type RawRecord = Record<string, unknown>;

export function validateAgentTeamDefinition(
  value: unknown,
  filePath: string,
  agentConfigs: Record<string, unknown>,
  resolveInstructions?: (roleId: TeamRoleId, instructionsPath: string) => string | null,
): AgentTeamValidationResult {
  const errors: string[] = [];
  if (!isRecord(value)) {
    return { errors: ['Team YAML must be an object.'] };
  }

  if (value.version !== 1) {
    errors.push('version must be 1.');
  }

  const id = readRequiredString(value, 'id', errors);
  const title = readRequiredString(value, 'title', errors);

  const orchestratorValue = value.orchestrator;
  if (orchestratorValue !== undefined) {
    if (!isRecord(orchestratorValue)) {
      errors.push('orchestrator must be an object.');
    } else {
      const orchestratorAgent = readRequiredString(orchestratorValue, 'agent', errors, 'orchestrator');
      if (orchestratorAgent && !agentConfigs[orchestratorAgent]) {
        errors.push(`orchestrator.agent references missing ACP agent "${orchestratorAgent}".`);
      }
    }
  }

  const rolesValue = value.roles;
  const roles: Partial<Record<TeamRoleId, TeamRoleDefinition>> = {};

  if (!isRecord(rolesValue)) {
    errors.push('roles must be an object.');
  } else {
    for (const key of Object.keys(rolesValue)) {
      if (!ALLOWED_TEAM_ROLES.includes(key as TeamRoleId)) {
        errors.push(`roles.${key} is not an allowed role in v1.`);
      }
    }

    for (const roleId of REQUIRED_TEAM_ROLES) {
      const roleValue = rolesValue[roleId];
      if (!isRecord(roleValue)) {
        errors.push(`roles.${roleId} is required and must be an object.`);
        continue;
      }

      for (const forbidden of FORBIDDEN_ROLE_KEYS) {
        if (forbidden in roleValue) {
          errors.push(`roles.${roleId}.${forbidden} is not allowed in team YAML (generated by compiler).`);
        }
      }

      const agent = readRequiredString(roleValue, 'agent', errors, `roles.${roleId}`);
      const instructions = readRequiredString(roleValue, 'instructions', errors, `roles.${roleId}`);

      if (agent && !agentConfigs[agent]) {
        errors.push(`roles.${roleId}.agent references missing ACP agent "${agent}".`);
      }

      if (instructions && resolveInstructions) {
        const resolved = resolveInstructions(roleId, instructions);
        if (resolved === null) {
          errors.push(`roles.${roleId}.instructions could not be resolved from "${instructions}".`);
        }
      }

      if (agent && instructions) {
        roles[roleId] = { agent, instructions };
      }
    }

    const testerValue = rolesValue.tester;
    if (testerValue !== undefined) {
      if (!isRecord(testerValue)) {
        errors.push('roles.tester must be an object when present.');
      } else {
        for (const forbidden of FORBIDDEN_ROLE_KEYS) {
          if (forbidden in testerValue) {
            errors.push(`roles.tester.${forbidden} is not allowed in team YAML.`);
          }
        }
        const agent = readRequiredString(testerValue, 'agent', errors, 'roles.tester');
        const instructions = readRequiredString(testerValue, 'instructions', errors, 'roles.tester');
        if (agent && !agentConfigs[agent]) {
          errors.push(`roles.tester.agent references missing ACP agent "${agent}".`);
        }
        if (instructions && resolveInstructions) {
          const resolved = resolveInstructions('tester', instructions);
          if (resolved === null) {
            errors.push(`roles.tester.instructions could not be resolved from "${instructions}".`);
          }
        }
        if (agent && instructions) {
          roles.tester = { agent, instructions };
        }
      }
    }
  }

  if (errors.length > 0 || !id || !title) {
    return { errors };
  }

  const completeRoles = roles as AgentTeamDefinition['roles'];
  for (const roleId of REQUIRED_TEAM_ROLES) {
    if (!completeRoles[roleId]) {
      return { errors: errors.length > 0 ? errors : [`roles.${roleId} is required.`] };
    }
  }

  return {
    definition: {
      version: 1,
      id,
      title,
      orchestrator: isRecord(orchestratorValue) && typeof orchestratorValue.agent === 'string'
        ? { agent: orchestratorValue.agent.trim() }
        : undefined,
      roles: completeRoles,
    },
    errors: [],
  };
}

function readRequiredString(
  record: RawRecord,
  key: string,
  errors: string[],
  scope = 'team',
): string {
  const value = record[key];
  if (typeof value !== 'string' || value.trim().length === 0) {
    errors.push(`${scope} ${key} must be a non-empty string.`);
    return '';
  }
  return value.trim();
}

function isRecord(value: unknown): value is RawRecord {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
