import type { ChatHistoryItem, MarkdownRenderedItem, MessageHistoryItem, ModelsState, ModesState, PersistedWebviewState, PipelinePlanHistoryItem, PipelineRoleOutputHistoryItem, PlanEntry, PlanHistoryItem, PlanUpdate, SessionSnapshot, SessionConfigOption, SessionUpdate, SlashCommand, ThoughtHistoryItem, ToolCallHistoryItem, ToolCallStatus } from '../chatTypes';
export declare function normalizeModesState(value: unknown): ModesState | null;
export declare function normalizeModelsState(value: unknown): ModelsState | null;
export declare function normalizeSlashCommands(value: unknown): SlashCommand[];
export declare function normalizeConfigOptions(value: unknown): SessionConfigOption[];
export declare function normalizeSessionSnapshot(value: unknown): SessionSnapshot | null;
export declare function normalizePlanEntry(entry: unknown): PlanEntry | null;
export declare function normalizePlanUpdate(value: unknown): PlanUpdate;
export declare function normalizeMarkdownRenderedItems(value: unknown): MarkdownRenderedItem[];
export declare function normalizeSessionUpdate(value: unknown): SessionUpdate;
export declare function normalizeMessageHistoryItem(value: unknown): MessageHistoryItem | null;
export declare function normalizePipelinePlanHistoryItem(value: unknown): PipelinePlanHistoryItem | null;
export declare function normalizePipelineRoleOutputHistoryItem(value: unknown): PipelineRoleOutputHistoryItem | null;
export declare function normalizeThoughtHistoryItem(value: unknown): ThoughtHistoryItem | null;
export declare function normalizeToolCallHistoryItem(value: unknown): ToolCallHistoryItem | null;
export declare function normalizePlanHistoryItem(value: unknown): PlanHistoryItem | null;
export declare function normalizeChatHistoryItem(value: unknown): ChatHistoryItem | null;
export declare function normalizePersistedState(value: unknown): PersistedWebviewState;
export declare function normalizeToolCallStatus(status: unknown): ToolCallStatus;
